### ISSUE TITLE
Linux Essential or Useful Toolkits? It is the problem.

### ISSUE THREAD

**Issue by lnxpy** [malijani/linux-essentials#2]
Hey Mohammad, 

It really amazed me. It's gonna be a good choice for those who want to start using Linux distributions. Kind of a short handy manual for starters. I think It's sorta a mini cook-book for becoming a little bit familiar to Linux. 
Hope hear for you soon. :)

Thanks again bro. :heart:

**Comment by malijani** [comment]
Hi,
I really appreciate your response to this project :heart: , Yeah It's a handbook for linux begginers and i like to finish it as soon as possible to throw it into the Iranian Linux community... just a fast guide to understand "What is linux?!", 
There are so many book out there. but I'll do my best :100:
:rose:

**Comment by lnxpy** [comment]
How nice!
Best wishes for you dear :D :heart:
